// netlify/functions/fortune.js
// Serverless function for the 2026 Auspicious Year Report
//
// Environment variables (set in Netlify -> Project configuration -> Environment variables):
//   OPENAI_API_KEY  -> your OpenAI API key
//   EXPIRY_DATE     -> e.g., 2026-04-30
//   SIGN_OFF_HTML   -> optional override for sign-off (otherwise default below is used)

const OPENAI_API_KEY = process.env.OPENAI_API_KEY;
const EXPIRY_DATE = process.env.EXPIRY_DATE || "2026-04-30";

const EXPIRY_MESSAGE = "This service has ended. Thank you for your interest.";

// Helper: JSON response
function json(body, status = 200) {
  return {
    statusCode: status,
    headers: {
      "Content-Type": "application/json",
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Headers": "Content-Type",
      "Access-Control-Allow-Methods": "POST, OPTIONS"
    },
    body: JSON.stringify(body)
  };
}

// Helper: build the prompt for OpenAI
function buildPrompt(dob) {
  return `
You are a modern feng shui and astrology master preparing a concise but meaningful
2026 annual forecast.

User's date of birth: ${dob} (format DDMMMYYYY)

Tasks:
1. Derive the user's relevant Chinese zodiac, five elements balance, and general luck cycle.
2. Give a 2026 overview across these sections:
   - Overall Luck & Themes
   - Wealth & Career
   - Relationships & Family
   - Health & Well-being
   - Auspicious Months & Key Dates (high level, no exact times)
   - Practical Dos & Don'ts for 2026

Style & format:
- Answer ONLY in clean HTML (no <html>, <head>, or <body> tags).
- Use <h2> section headings and <p> or <ul><li> for details.
- Keep the total length around 350–400 English words.
- Tone: warm, balanced, encouraging. No fear-mongering or absolute predictions.
- Do NOT mention that this is generated by AI.
- Do NOT give gambling or speculation tips.
- Assume the user is based in Singapore and frame examples appropriately.
`;
}

// Helper: sign-off block (you can override via SIGN_OFF_HTML env var if you want)
function buildSignOffHtml() {
  if (process.env.SIGN_OFF_HTML) return process.env.SIGN_OFF_HTML;

  return `
<div style="margin-top:1.5rem; padding:1rem 1.25rem; border-radius:12px; background:#fff5e6; border:1px solid #ffc266;">
  <p style="margin:0 0 0.5rem 0; font-weight:600;">
    — Prepared by <strong>Mike Lim</strong>, CEA Reg No. R026708F
  </p>
  <p style="margin:0.25rem 0;">
    📞 <a href="tel:+6596929209" style="color:#d35400; text-decoration:none;">+65 9692 9209</a>
  </p>
  <p style="margin:0.25rem 0;">
    <strong>SGHomeCompass</strong> | Your Chapter in Home Transition
  </p>
  <p style="margin:0.25rem 0;">
    🔗 
    <a href="https://www.youtube.com/@SGHomeCompass" target="_blank" rel="noopener noreferrer">YouTube</a> |
    <a href="https://www.instagram.com/sghomecompass/" target="_blank" rel="noopener noreferrer">Instagram</a>
  </p>
</div>
`;
}

// Main handler
exports.handler = async (event) => {
  // CORS preflight
  if (event.httpMethod === "OPTIONS") {
    return json({}, 200);
  }

  if (event.httpMethod === "GET") {
    return json({ message: "Use POST /.netlify/functions/fortune" }, 200);
  }

  if (event.httpMethod !== "POST") {
    return json({ message: "Method not allowed" }, 405);
  }

  if (!OPENAI_API_KEY) {
    console.error("Missing OPENAI_API_KEY");
    return json({ message: "Server error. Please try again later." }, 500);
  }

  try {
    const now = new Date();
    const expiry = new Date(EXPIRY_DATE + "T23:59:59Z");
    if (now > expiry) {
      return json({ resultHtml: `<p>${EXPIRY_MESSAGE}</p>` }, 200);
    }

    const body = JSON.parse(event.body || "{}");
    const dob = (body.dob || "").trim().toUpperCase();

    // Basic validation: DDMMMYYYY (e.g., 08DEC1977)
    const dobPattern = /^\d{2}[A-Z]{3}\d{4}$/;
    if (!dobPattern.test(dob)) {
      return json(
        { message: "Please use DDMMMYYYY format, e.g., 08DEC1977." },
        400
      );
    }

    const prompt = buildPrompt(dob);

    // Call OpenAI Chat Completions API directly using fetch
    const apiRes = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${OPENAI_API_KEY}`
      },
      body: JSON.stringify({
        model: "gpt-4o-mini",
        messages: [
          {
            role: "system",
            content:
              "You are an experienced feng shui and astrology master preparing 2026 forecasts in clean HTML."
          },
          {
            role: "user",
            content: prompt
          }
        ],
        max_tokens: 500,
        temperature: 0.7
      })
    });

    if (!apiRes.ok) {
      const errText = await apiRes.text();
      console.error("OpenAI API error:", apiRes.status, errText);
      return json({ message: "Server error. Please try again later." }, 500);
    }

    const data = await apiRes.json();
    const text =
      (data.choices &&
        data.choices[0] &&
        data.choices[0].message &&
        data.choices[0].message.content) ||
      "";

    const cleaned = (text || "").trim();

    if (!cleaned) {
      console.error("Empty completion from OpenAI:", JSON.stringify(data));
      return json({ message: "Server error. Please try again later." }, 500);
    }

    const signOffHtml = buildSignOffHtml();
    const resultHtml = `${cleaned}\n${signOffHtml}`;

    return json({ resultHtml }, 200);
  } catch (err) {
    console.error("Handler error:", err);
    return json({ message: "Server error. Please try again later." }, 500);
  }
};
